<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<#--    <link rel="stylesheet" href="./style/outlines.css">-->
    <link rel="stylesheet" href="./style/common.css">
    <meta charset="UTF-8">
    <meta name="description" content="This is the website of Iaroslav Sviridov's portfolio">
    <meta name="keywords" content="Sviridov Iaroslav, Sviridov Yaroslav, Java, C#, C++, backend, programmer">
    <meta name="author" content="Sviridov Iaroslav">
    <title>Sviridov Iaroslav</title>
</head>
<body>
    <aside>
        <section class="personality">
            <div class="avatarContainer">
                <img class="avatar" src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar">
            </div>
            <div class="nameContainer">
                <h1>Sviridov </br> Iaroslav</h1>
            </div>
        </section>
        <nav>
            <a href="#about">About</a>
            <a href="#education">Education</a>
            <a href="#experience">Work experience</a>
            <a href="#skills">Skills</a>
        </nav>
        <form class="downloadCvSection">
            <button formaction="/docs/cv.pdf">Download CV</button>
        </form>
        <section class="contacts">
            <a href="https://github.com/Spolutrean">
                <img src="img/github.png">
            </a>
            <a href="mailto:ys9617890962@gmail.com">
                <img src="img/email.png">
            </a>
            <a href="https://t.me/spolutrean">
                <img src="img/telegram.png">
            </a>
        </section>
    </aside>
    <main>
        <section class="section section_about" id="about"></section>
        <section class="section section_education" id="education"></section>
        <section class="section section_experience" id="experience"></section>
        <section class="section section_skills" id="skills"></section>
    </main>
</body>
</html>